### ISSUE TITLE
code suggestion

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [mishakorzik/UserFinder#3]
```

printf "\e[1;77m __   __  ______  _______  ______      _______  ___  __    _  ______   _______  ______ \e[0m\n"
printf "\e[1;77m|  | |  ||      ||       ||    _ |    |       ||   ||  |  | ||      | |       ||    _ |\e[0m\n"
printf "\e[1;77m|  | |  ||  ____||    ___||   | ||    |    ___||   ||   |_| ||  _    ||    ___||   | ||\e[0m\n"
printf "\e[1;77m|  |_|  || |____ |   |___ |   |_||_   |   |___ |   ||       || | |   ||   |___ |   |_||_ \e[0m\n"
printf "\e[1;77m|       ||____  ||    ___||    __  |  |    ___||   ||  _    || |_|   ||    ___||    __  |\e[0m\n"
printf "\e[1;77m|       | ____| ||   |___ |   |  | |  |   |    |   || | |   ||       ||   |___ |   |  | |\e[0m\n"
printf "\e[1;77m|_______||______||_______||___|  |_|  |___|    |___||_|  |__||______| |_______||___|  |_|\e[0m\n"
printf "\n"
printf "\e[1;93m             .:.:;..\e[0m\e[1;77m UserFinder v1.0 Developer: misha korzhik \e[0m\e[1;93m..;:.:.\e[0m\n"
printf "\n"
```

you should probobly put this in a txt file, then just have bash 

Cat banner.txt 

then color the banner

**Comment by mishakorzik** [comment]
why? If it will be easier to do everything in one file.

**Comment by ArkAngeL43** [comment]
it actually wouldnt, by the time you make, copy and paste all the print commands and format the banner, you could ahve just put `cat banner.txt` and boom done, alot easier than print, printf, echo -e, etc

**Comment by mishakorzik** [comment]
Yes, you are right, but it will be more comfortable when everything is in one code.  And so more practical.

**Comment by hossemtamsouh** [comment]
hi i need a help what is the meaning of this error "UserFinder.sh: ligne 362: $username.txt : redirection ambiguë
"

**Comment by ArkAngeL43** [comment]
it means the file was not created meaning you probobly have not run the tool before, im sure the script will create the file once  youve run it

**Comment by hossemtamsouh** [comment]
> it means the file was not created meaning you probobly have not run the tool before, im sure the script will create the file once youve run it

thanks for your help.
