### ISSUE TITLE
This tool is inferior to the existing tools (such as https://github.com/sherlock-project/sherlock)

### ISSUE THREAD

**Issue by KOLANICH** [mishakorzik/UserFinder#6]

**Comment by mishakorzik** [comment]
not at all, the sherlock tool uses python and a large number of modules. And my tool uses bash.

If you even look at the sherlock code, there is nothing similar between them.

**Comment by KOLANICH** [comment]
>uses python and a large number of modules. And my tool uses bash.

It is advantage. Bash is an awful language unsuitable for anything serious.

>If you even look at the sherlock code, there is nothing similar between them.

The function is similar - checking presence of a certain nickname on multiple services.

**Comment by mishakorzik** [comment]
why do you think so?  The advantage of my tool is that you don't need to install dependencies, just install the script.

Bash is a normal programming language, it is used in many Linux terminals.

**Comment by KOLANICH** [comment]
python is alredy an essential component of all distros.

**Comment by mishakorzik** [comment]
Okay

**Comment by mishakorzik** [comment]
This UserFinder was written 2 years ago. At that time, bash was most widely used in linux

**Comment by KOLANICH** [comment]
No, python used to be a mandatory component for a pretty long time. At least for desktop distros (I guess this tool is intended to be used on desktops), like Ubuntu and Debian, I don't mean stripped to the bones alpine-based Docker images.

**Comment by mishakorzik** [comment]
Okay
